In [11]:
from pynq.overlays.base import BaseOverlay
from pynq.lib.video import *

base = BaseOverlay("projecttest.bit")
hdmi_in = base.video.hdmi_in
hdmi_out = base.video.hdmi_out

In [12]:
PIXEL_BGRA = PixelFormat(32, COLOR_IN_BGR, COLOR_OUT_BGR, "BG24")
hdmi_in.configure()
hdmi_out.configure(hdmi_in.mode, )

hdmi_in.start()
hdmi_out.start()

In [ ]:
from pynq import MMIO
#filter_reference = MMIO(0x00000000,0x10000)
filter_reference = MMIO(0x83C20000,0x10000)  #MMIO Addresses should always be double-checked when exporting a Vivado Design

In [ ]:
in_frame = hdmi_in.readframe()
print(in_frame)

In [ ]:
#import cv2
for i in range(100):
    in_frame = hdmi_in.readframe()
    out_frame = hdmi_out.newframe()
    CookieX= 0;
    CookieY= 0;
    CookieW= 0;
    
    ElmoX= 0;
    ElmoY= 0;
    ElmoW= 0;
    
    filter_reference.write(0x10, in_frame.physical_address)   # Get Pointers to memory
    filter_reference.write(0x18, out_frame.physical_address)
    #filter_reference.write(0x20, CookieX)
    #filter_reference.write(0x28, CookieY)
    #filter_reference.write(0x38, CookieW)
    #filter_reference.write(0x40, ElmoX)
    #filter_reference.write(0x48, ElmoY)
    #filter_reference.write(0x58, ElmoW)

        
    
    #filter_reference.write(0x20, 1280)   # Make sure that the input HDMI signal is set to 1280x720
    #filter_reference.write(0x28, 720)
    #filter_reference.write(0x20, in_frame.shape[1]) 
    #filter_reference.write(0x28, in_frame.shape[0])
    #filter_reference.write(0x00, 0x01)             # ap_start triggering
    #while (filter_reference.read(0) & 0x4) == 0:   # ap_done checking
    #    pass
    #print(out_frame)
    hdmi_out.writeframe(out_frame)
    
   # print("Cookie: ", CookieX, ",", CookieY, " w:", CookieW)
        
    #if (ElmoX != 0):
    #    print("Elmo: ", ElmoX, ",", ElmoY, " w:", ElmoW)


NEW CODE

In [ ]:
import cv2
#import numpy as np
import random

imgCookie = cv2.imread('cookie.png')
imgHeart = cv2.imread("heart.png")
imgBroc = cv2.imread('art.png')

frame_count = 0

cookie_point_across_one = random.randint(50, 1770)
cookie_point_across_two = random.randint(50,1770)
cookie_point_across_three = random.randint(50,1770)
broc_point_across = random.randint(50,1770)
        
allgood = True



while(allgood):
    if abs(cookie_point_across_two-cookie_point_across_one) < 75:
        cookie_point_across_two = random.randint(50,1770)
    if abs(cookie_point_across_one-cookie_point_across_three) < 75:
        cookie_point_across_three = random.randint(50,1770)
    elif abs(cookie_point_across_two-cookie_point_across_three) < 75:
        cookie_point_across_three = random.randint(50,1770)
    else:
        allgood = False
            
allgood = True

while(allgood):
    if abs(broc_point_across-cookie_point_across_one) > 75 and abs(broc_point_across-cookie_point_across_two) > 75 and abs(broc_point_across-cookie_point_across_three) > 75:
        allgood = False
    else:
        broc_point_across = random.randint(50,1770)
            
cookie_point_down_one = 0
cookie_point_down_two = 0
cookie_point_down_three = 0
broc_point_down = 0
#lower is faster
cookie_speed = 2     
lives = 3

#while(True):
for _ in range (2000):
    frame = hdmi_in.readframe()
    
     
    cookie_h, cookie_w, cookie_c = imgCookie_one.shape
    broc_h, broc_w, broc_c = imgBroc.shape
    
    
    if frame_count%cookie_speed == 0:
        cookie_point_down_one = cookie_point_down_one+5
        cookie_point_down_two = cookie_point_down_two+20
        cookie_point_down_three = cookie_point_down_three+20
        broc_point_down = broc_point_down+20
        
    if cookie_point_down_one >= 1010:
        lives = lives - 1
        if lives > 0:
            cookie_point_across_one = random.randint(50,1770)
            allgood = True
            while(allgood):
                if abs(cookie_point_across_one-cookie_point_across_two) > 75 and abs(cookie_point_across_one-cookie_point_across_three) > 75:
                    allgood = False
                else:
                    cookie_point_across_one = random.randint(50,1770)
            cookie_point_down_one = 0
    
    heart_h, heart_w, heart_c = imgHeart.shape
    
    #Printing the hearts
    
    frame_h, frame_w, frame_c = frame.shape
    overlay = np.zeros((frame_h, frame_w, 4), dtype='uint8')
    
    
    if lives == 3:
        yoff = 0
        xoff = 1870
        frame[yoff:yoff+imgHeart.shape[0], xoff:xoff+imgHeart.shape[1]] = imgHeart
        yoff = 0
        xoff = 1820
        frame[yoff:yoff+imgHeart.shape[0], xoff:xoff+imgHeart.shape[1]] = imgHeart
        yoff = 0
        xoff = 1770
        frame[yoff:yoff+imgHeart.shape[0], xoff:xoff+imgHeart.shape[1]] = imgHeart

                
    if lives == 2:
        yoff = 0
        xoff = 1870
        frame[yoff:yoff+imgHeart.shape[0], xoff:xoff+imgHeart.shape[1]] = imgHeart       
        yoff = 0
        xoff = 1820
        frame[yoff:yoff+imgHeart.shape[0], xoff:xoff+imgHeart.shape[1]] = imgHeart
      #  overlay = np.zeros((frame_h, frame_w, 4), dtype='uint8')
      #  for i in range(0,heart_h):
      #      for j in range(0,heart_w):
      #          overlay[i, j+1770] = imgHeart[i, j]
       # cv2.addWeighted(overlay, 0.6, frame, 1.0, 0, frame)
            
     
    if lives == 1:
        yoff = 0
        xoff = 1870
        frame[yoff:yoff+imgHeart.shape[0], xoff:xoff+imgHeart.shape[1]] = imgHeart
       # overlay = np.zeros((frame_h, frame_w, 4), dtype='uint8')
       # for i in range(0,heart_h):
       #     for j in range(0,heart_w):
       #         overlay[i, j+1820] = imgHeart[i, j]
       # cv2.addWeighted(overlay, 0.6, frame, 1.0, 0, frame)
        #overlay = np.zeros((frame_h, frame_w, 4), dtype='uint8')
        #for i in range(0,heart_h):
        #    for j in range(0,heart_w):
         #       overlay[i, j+1770] = imgHeart[i, j]
       # cv2.addWeighted(overlay, 0.6, frame, 1.0, 0, frame)
        
    #if lives <= 0:
     #   overlay = np.zeros((frame_h, frame_w, 4), dtype='uint8')
     #   for i in range(0,heart_h):
      #      for j in range(0,heart_w):
       #         overlay[i, j+1870] = imgHeart[i, j]
   #     cv2.addWeighted(overlay, 0.6, frame, 1.0, 0, frame)
    #    overlay = np.zeros((frame_h, frame_w, 4), dtype='uint8')
     #   for i in range(0,heart_h):
  #         for j in range(0,heart_w):
  #              overlay[i, j+1820] = imgHeart[i, j]
  #      cv2.addWeighted(overlay, 0.6, frame, 1.0, 0, frame)
  #      overlay = np.zeros((frame_h, frame_w, 4), dtype='uint8')
  #      for i in range(0,heart_h):
  #          for j in range(0,heart_w):
  #              overlay[i, j+1770] = imgHeart[i, j]
  #      cv2.addWeighted(overlay, 0.6, frame, 1.0, 0, frame)
        
        
    #Printing the cookies and broc
    
    if lives > 0:
        yoff = cookie_point_down_one
        xoff = cookie_point_across_one
        frame[yoff:yoff+imgCookie.shape[0], xoff:xoff+imgCookie.shape[1]] = imgCookie        
        yoff = cookie_point_down_two
        xoff = cookie_point_across_two
        frame[yoff:yoff+imgCookie.shape[0], xoff:xoff+imgCookie.shape[1]] = imgCookie    
        yoff = cookie_point_down_three
        xoff = cookie_point_across_three
        frame[yoff:yoff+imgCookie.shape[0], xoff:xoff+imgCookie.shape[1]] = imgCookie           
        #yoff = broc_point_down
        #xoff = broc_point_across
        #frame[yoff:yoff+imgBroc.shape[0], xoff:xoff+imgBroc.shape[1]] = imgBroc
    
    if lives == 0:
        font = cv2.FONT_HERSHEY_TRIPLEX
        cv2.putText(frame, 'GAME OVER', (400, 500), font, 6, (255,255,255), 2, cv2.LINE_AA)
        
    hdmi_out.writeframe(frame)  
    
    frame_count = frame_count + 1
    




In [13]:
import cv2
#import numpy as np
import random

imgCookie = cv2.imread('cookie.png')
#print(imgCookie)
#imgCookie = cv2.cvtColor(imgCookie, cv2.COLOR_BGR2BGR)


import time

numframes = 100
start = time.time()

for i in range(numframes):
    frame = hdmi_in.readframe()
    print(frame)
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGBA)
    print(frame)

     
    cookie_h, cookie_w, cookie_c = imgCookie.shape
    yoff = 200
    xoff = 600
    
    frame[yoff:yoff+imgCookie.shape[0], xoff:xoff+imgCookie.shape[1]] = imgCookie

                
    #frame = cv2.flip(frame,1)
    hdmi_out.writeframe(frame)  

end = time.time()
print(hdmi_out.mode)

print("Frames per second:  " + str(numframes / (end - start)))
    
    




[[[230 225 222]
  [230 225 222]
  [230 225 222]
  ..., 
  [230 225 222]
  [230 225 222]
  [230 225 222]]

 [[230 225 222]
  [230 225 222]
  [230 225 222]
  ..., 
  [230 225 222]
  [230 225 222]
  [230 225 222]]

 [[230 225 222]
  [230 225 222]
  [230 225 222]
  ..., 
  [230 225 222]
  [230 225 222]
  [230 225 222]]

 ..., 
 [[ 33  41  35]
  [ 34  42  36]
  [ 34  42  36]
  ..., 
  [ 33  41  38]
  [ 32  40  37]
  [ 32  40  37]]

 [[ 35  43  37]
  [ 34  42  36]
  [ 35  43  37]
  ..., 
  [ 33  41  38]
  [ 33  41  38]
  [ 35  43  40]]

 [[ 35  43  37]
  [ 35  43  37]
  [ 36  44  39]
  ..., 
  [ 33  41  38]
  [ 32  40  37]
  [ 31  39  36]]]
[[[222 225 230 255]
  [222 225 230 255]
  [222 225 230 255]
  ..., 
  [222 225 230 255]
  [222 225 230 255]
  [222 225 230 255]]

 [[222 225 230 255]
  [222 225 230 255]
  [222 225 230 255]
  ..., 
  [222 225 230 255]
  [222 225 230 255]
  [222 225 230 255]]

 [[222 225 230 255]
  [222 225 230 255]
  [222 225 230 255]
  ..., 
  [222 225 230 255]
  [222 22

ValueError: could not broadcast input array from shape (75,75,3) into shape (75,75,4)

In [14]:
hdmi_in.close()    # Don't forget to run this to free memory
hdmi_out.close()   # NEVERFORGET NEVERFORGET NEVERFORGET :p 